spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.jskillcloud: debug
